from pathlib import Path


def read_file(repo_path: str, file_path: str, max_chars: int = 20_000) -> str:
    root = Path(repo_path).resolve()
    target = (root / file_path).resolve()

    # Always verify path generated by model
    if not target.is_relative_to(root):
        raise ValueError("File path escapes repository")

    if not target.is_file():
        raise FileNotFoundError(file_path)

    return target.read_text(
        encoding="utf-8",
        errors="replace",
    )[:max_chars]
